### ISSUE TITLE
Support for Solus OS

### ISSUE THREAD

**Issue by Abhinav1217** [gotbletu/serverscripts#1]
Hi, I saw your youtube video on this few minutes ago, and tried it on my fedora machine. It solves so many of my headaches that I can't thank you enough. As usual your scripts are really helpful. I am currently trying it on My Solus machine. 

I have forked and I am updating the script to work on my Solus machine. I have already fixed `find_pkm()` to look for eopkg ( the package manager of solus ) and fixed `install-samba.sh`.  But I need to cleanup my existing badly configured samba for the `addnew-sambauser.sh` to work properly, Currently it is not working. 

I will work on it in the morning. I would love to send a PR for this enhancement if you like.

**Comment by gotbletu** [comment]
sure the more the better, i just dont no all the package managers or service name they got, but is easy to edit =)

**Comment by Abhinav1217** [comment]
Initiated a PR #2  for your review.

**Comment by Abhinav1217** [comment]
Merged #2
